// Copyright 2023 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP22
#define I2C1_SCL_PIN GP23

#define AUDIO_PIN GP28
#define AUDIO_PWM_DRIVER PWMD6
#define AUDIO_INIT_DELAY
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define STARTUP_SONG SONG()

//#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
//#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
//#define ANALOG_JOYSTICK_SPEED_MAX 4
//#define POINTING_DEVICE_INVERT_Y
// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 5
#define MOUSEKEY_MOVE_DELTA 5
//#define MOUSEKEY_BASE_SPEED 3000
//#define MOUSEKEY_ACCELERATED_SPEED 1500
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 45
//#define MK_KINETIC_SPEED

#define DEBOUNCE 15
